// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACxKmSElDz1gOi5ORObECOx1Pw830mgrU',
    appId: '1:453015020866:android:94335cd46e45384a3ed4db',
    messagingSenderId: '453015020866',
    projectId: 'gojo-s',
    databaseURL: 'https://gojo-s-default-rtdb.firebaseio.com',
    storageBucket: 'gojo-s.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbyGcGkH-tQFdSIjBUo432MENg4ulXlLQ',
    appId: '1:453015020866:ios:5195f545afc209d03ed4db',
    messagingSenderId: '453015020866',
    projectId: 'gojo-s',
    databaseURL: 'https://gojo-s-default-rtdb.firebaseio.com',
    storageBucket: 'gojo-s.appspot.com',
    iosClientId: '453015020866-ga68jn2rdf91q796qrbnppk0nuvtv1le.apps.googleusercontent.com',
    iosBundleId: 'com.example.gojo',
  );

}